### ISSUE TITLE
You can change this setting?

### ISSUE THREAD

**Issue by Abo233** [CplPibald/PiTweaks#11]
before
Apply enchanted books to any item in an anvil, ignoring item type and conflicting enchantments.  Now you can finally put both Infinity and Mending on your favorite bow.  Or Bane of Arthropods on a stack of dirt blocks.  I don't judge.  (New in version 1.1.0) 

after
Apply enchanted books ignoring conflicting enchantments.

Ignore item type is too abnormal condition and there are too many bugs

**Comment by CplPibald** [comment]
Not sure what you mean by "too many bugs".  If you have some good examples where this breaks the game, please explain and I can try to split out the config.  If the only problem is that it's "abnormal" or feels weird to put protection on a hoe or unbreaking on cobblestone, then don't do that in your game.

Closing because of stale issue
