### ISSUE TITLE
[1.12.2] PiTweaks Overriding CraftTweaker Recipes

### ISSUE THREAD

**Issue by jonqrandom** [CplPibald/PiTweaks#3]
i have [the following](https://paste.ee/p/mH8Pw) in my recipes.zs, the button recipes are working fine, the pressure plate recipes are being overriden by pitweaks. please could you avoid overwriting recipe changes made by crafttweaker (and other recipe managers), as they should always be the final decider in any pack. in my particular circumstance, the pitweaks recipe for pressure plates is conflicting with quark's generic slabs-to-blocks recipe, and i'm not prepared to release a pack that relies on NoMoreRecipeConflict to function.

**Comment by CplPibald** [comment]
What does "conflicting" mean here?  Are you not able to convert slabs to blocks using the Quark recipe?  PiTweaks adds a slab-to-blocks recipe that's shapeless, so you should be able to get the blocks back by putting them anywhere in the grid.

The 2x2 recipes tweak is probably not compatible with Quark anyway because they both try to tweak stair and slab recipes, and they both add a slab-to-block recipe.  If you're using Quark, you might want to turn off the 2x2 tweak.

Right now, PiTweaks just scans the recipe list for stair/slab recipes and adds the new ones dynamically (same as Quark).  I have no control over when other mods' recipes get added.  I'll see if I can make it more aware of existing recipes though.

**Comment by jonqrandom** [comment]
i'm not asking you to change recipes, i can (normally) deal with recipe conflicts just fine. i was mentioning the particular issue that brought this to light, but it's not the root of the problem. i have
`recipes.remove(<minecraft:wooden_pressure_plate>);
recipes.remove(<minecraft:stone_pressure_plate>);`
in my script, yet _i'm still seeing pitweaks pressure plates recipes, and not the ones i add. JEI is quite specific that the recipe (2x stone/wood slabs) comes from pitweaks._ i can check crafttweaker's docs, but as far as i'm aware it's loading its changes as late as possible in order to be able to override everything else.

**Comment by BloodWorkXGaming** [comment]
Here is a suggestion so that you don't have to redesign your whole existing recipe checks and stuff:

you could add `dependencies="before:crafttweaker"` to you `@Mod` annotation to load before crt so the post init events don't conflict with each other.
Current problem is that P is after C in the alphabet and therefore it is able to overwrite it.

This will _not_ give you a hard dependency on crafttweaker.

**Comment by CplPibald** [comment]
I decided to go with a simpler approach.  I added a config option to disable all pressure plate handling in PiTweaks, so that people using crafttweaker can customize however they want and my mod will stay out of the way.

Does this solve your problem?

**Comment by jonqrandom** [comment]
sure, that'll do it, thanks :)
